[
    {
        "line_id": 0,
        "red_app_id": "76074884",
        "cmpt_id": 77960665,
        "cmpt_name": "Unicode for C Sharp (Unicode4C)",
        "cmpt_version": "67.9",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "Unicode License V7",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "76654",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 1,
        "red_app_id": "76074884",
        "cmpt_id": 77960665,
        "cmpt_name": "Unicode for C Sharp (Unicode4C)",
        "cmpt_version": "67.9",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "Unicode License V7",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "76654",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 2,
        "red_app_id": "76074884",
        "cmpt_id": 69676778,
        "cmpt_name": "kassandra\/xerces-c",
        "cmpt_version": "6.7.7",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "48023",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 3,
        "red_app_id": "76074884",
        "cmpt_id": 69676778,
        "cmpt_name": "kassandra\/xerces-c",
        "cmpt_version": "6.7.7",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "48023",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 4,
        "red_app_id": "76074884",
        "cmpt_id": 755955,
        "cmpt_name": "Commons IO",
        "cmpt_version": "7.5",
        "app_id": 49823780,
        "app_name": "General ED",
        "app_version": "7.7.0.9",
        "license": "kassandra License 7.0",
        "status": "Rejected",
        "requester": "Barry Lind",
        "monitoring_id": "75896",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 5,
        "red_app_id": "76074884",
        "cmpt_id": 957948,
        "cmpt_name": "kassandra Commons Codec",
        "cmpt_version": "9.9",
        "app_id": 49823780,
        "app_name": "General ED",
        "app_version": "7.7.0.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Barry Lind",
        "monitoring_id": "76884",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 6,
        "red_app_id": "76074884",
        "cmpt_id": 9496865,
        "cmpt_name": "kassandra Jakarta Commons Codec",
        "cmpt_version": "9.6",
        "app_id": 80096980,
        "app_name": "General Te",
        "app_version": "96.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Clay Rowe",
        "monitoring_id": "9697",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 7,
        "red_app_id": "76074884",
        "cmpt_id": 7023877,
        "cmpt_name": "knockout - knockout\/knockout",
        "cmpt_version": "7.9.0",
        "app_id": 56704001,
        "app_name": "General Ac",
        "app_version": "4.0.9 - 5.0.0",
        "license": "MIT License",
        "status": "Submitted",
        "requester": "Clay Rowe",
        "monitoring_id": "94875",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 8,
        "red_app_id": "76074884",
        "cmpt_id": 7097666,
        "cmpt_name": "Oracle PHP API",
        "cmpt_version": "9.4.4",
        "app_id": 78784237,
        "app_name": "General Te",
        "app_version": "96.9",
        "license": "Unspecified",
        "status": "Approved",
        "requester": "Clay Rowe",
        "monitoring_id": "94649",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 9,
        "red_app_id": "76074884",
        "cmpt_id": 7097666,
        "cmpt_name": "Oracle PHP API",
        "cmpt_version": "9.4.4",
        "app_id": 78784237,
        "app_name": "General Te",
        "app_version": "96.9",
        "license": "Unspecified",
        "status": "Approved",
        "requester": "Clay Rowe",
        "monitoring_id": "94649",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 10,
        "red_app_id": "76074884",
        "cmpt_id": 77960665,
        "cmpt_name": "Unicode for C Sharp (Unicode4C)",
        "cmpt_version": "67.9",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "Unicode License V7",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "76654",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 11,
        "red_app_id": "76074884",
        "cmpt_id": 77960665,
        "cmpt_name": "Unicode for C Sharp (Unicode4C)",
        "cmpt_version": "67.9",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "Unicode License V7",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "76654",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 12,
        "red_app_id": "76074884",
        "cmpt_id": 69676778,
        "cmpt_name": "kassandra\/xerces-c",
        "cmpt_version": "6.7.7",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "48023",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 13,
        "red_app_id": "76074884",
        "cmpt_id": 69676778,
        "cmpt_name": "kassandra\/xerces-c",
        "cmpt_version": "6.7.7",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "48023",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 14,
        "red_app_id": "76074884",
        "cmpt_id": 755955,
        "cmpt_name": "Commons IO",
        "cmpt_version": "7.5",
        "app_id": 49823780,
        "app_name": "General ED",
        "app_version": "7.7.0.9",
        "license": "kassandra License 7.0",
        "status": "Rejected",
        "requester": "Barry Lind",
        "monitoring_id": "75896",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 15,
        "red_app_id": "76074884",
        "cmpt_id": 957948,
        "cmpt_name": "kassandra Commons Codec",
        "cmpt_version": "9.9",
        "app_id": 49823780,
        "app_name": "General ED",
        "app_version": "7.7.0.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Barry Lind",
        "monitoring_id": "76884",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 16,
        "red_app_id": "76074884",
        "cmpt_id": 9496865,
        "cmpt_name": "kassandra Jakarta Commons Codec",
        "cmpt_version": "9.6",
        "app_id": 80096980,
        "app_name": "General Te",
        "app_version": "96.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Clay Rowe",
        "monitoring_id": "9697",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 17,
        "red_app_id": "76074884",
        "cmpt_id": 7023877,
        "cmpt_name": "knockout - knockout\/knockout",
        "cmpt_version": "7.9.0",
        "app_id": 56704001,
        "app_name": "General Ac",
        "app_version": "4.0.9 - 5.0.0",
        "license": "MIT License",
        "status": "Submitted",
        "requester": "Clay Rowe",
        "monitoring_id": "94875",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 18,
        "red_app_id": "76074884",
        "cmpt_id": 7097666,
        "cmpt_name": "Oracle PHP API",
        "cmpt_version": "9.4.4",
        "app_id": 78784237,
        "app_name": "General Te",
        "app_version": "96.9",
        "license": "Unspecified",
        "status": "Approved",
        "requester": "Clay Rowe",
        "monitoring_id": "94649",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 19,
        "red_app_id": "76074884",
        "cmpt_id": 7097666,
        "cmpt_name": "Oracle PHP API",
        "cmpt_version": "9.4.4",
        "app_id": 78784237,
        "app_name": "General Te",
        "app_version": "96.9",
        "license": "Unspecified",
        "status": "Approved",
        "requester": "Clay Rowe",
        "monitoring_id": "94649",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 20,
        "red_app_id": "76074884",
        "cmpt_id": 77960665,
        "cmpt_name": "Unicode for C Sharp (Unicode4C)",
        "cmpt_version": "67.9",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "Unicode License V7",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "76654",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 21,
        "red_app_id": "76074884",
        "cmpt_id": 77960665,
        "cmpt_name": "Unicode for C Sharp (Unicode4C)",
        "cmpt_version": "67.9",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "Unicode License V7",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "76654",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 22,
        "red_app_id": "76074884",
        "cmpt_id": 69676778,
        "cmpt_name": "kassandra\/xerces-c",
        "cmpt_version": "6.7.7",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "48023",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 23,
        "red_app_id": "76074884",
        "cmpt_id": 69676778,
        "cmpt_name": "kassandra\/xerces-c",
        "cmpt_version": "6.7.7",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "48023",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 24,
        "red_app_id": "76074884",
        "cmpt_id": 755955,
        "cmpt_name": "Commons IO",
        "cmpt_version": "7.5",
        "app_id": 49823780,
        "app_name": "General ED",
        "app_version": "7.7.0.9",
        "license": "kassandra License 7.0",
        "status": "Rejected",
        "requester": "Barry Lind",
        "monitoring_id": "75896",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 25,
        "red_app_id": "76074884",
        "cmpt_id": 957948,
        "cmpt_name": "kassandra Commons Codec",
        "cmpt_version": "9.9",
        "app_id": 49823780,
        "app_name": "General ED",
        "app_version": "7.7.0.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Barry Lind",
        "monitoring_id": "76884",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 26,
        "red_app_id": "76074884",
        "cmpt_id": 9496865,
        "cmpt_name": "kassandra Jakarta Commons Codec",
        "cmpt_version": "9.6",
        "app_id": 80096980,
        "app_name": "General Te",
        "app_version": "96.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Clay Rowe",
        "monitoring_id": "9697",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 27,
        "red_app_id": "76074884",
        "cmpt_id": 7023877,
        "cmpt_name": "knockout - knockout\/knockout",
        "cmpt_version": "7.9.0",
        "app_id": 56704001,
        "app_name": "General Ac",
        "app_version": "4.0.9 - 5.0.0",
        "license": "MIT License",
        "status": "Submitted",
        "requester": "Clay Rowe",
        "monitoring_id": "94875",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 28,
        "red_app_id": "76074884",
        "cmpt_id": 7097666,
        "cmpt_name": "Oracle PHP API",
        "cmpt_version": "9.4.4",
        "app_id": 78784237,
        "app_name": "General Te",
        "app_version": "96.9",
        "license": "Unspecified",
        "status": "Approved",
        "requester": "Clay Rowe",
        "monitoring_id": "94649",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 29,
        "red_app_id": "76074884",
        "cmpt_id": 7097666,
        "cmpt_name": "Oracle PHP API",
        "cmpt_version": "9.4.4",
        "app_id": 78784237,
        "app_name": "General Te",
        "app_version": "96.9",
        "license": "Unspecified",
        "status": "Approved",
        "requester": "Clay Rowe",
        "monitoring_id": "94649",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 30,
        "red_app_id": "76074884",
        "cmpt_id": 77960665,
        "cmpt_name": "Unicode for C Sharp (Unicode4C)",
        "cmpt_version": "67.9",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "Unicode License V7",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "76654",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 31,
        "red_app_id": "76074884",
        "cmpt_id": 77960665,
        "cmpt_name": "Unicode for C Sharp (Unicode4C)",
        "cmpt_version": "67.9",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "Unicode License V7",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "76654",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 32,
        "red_app_id": "76074884",
        "cmpt_id": 69676778,
        "cmpt_name": "kassandra\/xerces-c",
        "cmpt_version": "6.7.7",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "48023",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 33,
        "red_app_id": "76074884",
        "cmpt_id": 69676778,
        "cmpt_name": "kassandra\/xerces-c",
        "cmpt_version": "6.7.7",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "48023",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 34,
        "red_app_id": "76074884",
        "cmpt_id": 755955,
        "cmpt_name": "Commons IO",
        "cmpt_version": "7.5",
        "app_id": 49823780,
        "app_name": "General ED",
        "app_version": "7.7.0.9",
        "license": "kassandra License 7.0",
        "status": "Rejected",
        "requester": "Barry Lind",
        "monitoring_id": "75896",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 35,
        "red_app_id": "76074884",
        "cmpt_id": 957948,
        "cmpt_name": "kassandra Commons Codec",
        "cmpt_version": "9.9",
        "app_id": 49823780,
        "app_name": "General ED",
        "app_version": "7.7.0.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Barry Lind",
        "monitoring_id": "76884",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 36,
        "red_app_id": "76074884",
        "cmpt_id": 9496865,
        "cmpt_name": "kassandra Jakarta Commons Codec",
        "cmpt_version": "9.6",
        "app_id": 80096980,
        "app_name": "General Te",
        "app_version": "96.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Clay Rowe",
        "monitoring_id": "9697",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 37,
        "red_app_id": "76074884",
        "cmpt_id": 7023877,
        "cmpt_name": "knockout - knockout\/knockout",
        "cmpt_version": "7.9.0",
        "app_id": 56704001,
        "app_name": "General Ac",
        "app_version": "4.0.9 - 5.0.0",
        "license": "MIT License",
        "status": "Submitted",
        "requester": "Clay Rowe",
        "monitoring_id": "94875",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 38,
        "red_app_id": "76074884",
        "cmpt_id": 7097666,
        "cmpt_name": "Oracle PHP API",
        "cmpt_version": "9.4.4",
        "app_id": 78784237,
        "app_name": "General Te",
        "app_version": "96.9",
        "license": "Unspecified",
        "status": "Approved",
        "requester": "Clay Rowe",
        "monitoring_id": "94649",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 39,
        "red_app_id": "76074884",
        "cmpt_id": 7097666,
        "cmpt_name": "Oracle PHP API",
        "cmpt_version": "9.4.4",
        "app_id": 78784237,
        "app_name": "General Te",
        "app_version": "96.9",
        "license": "Unspecified",
        "status": "Approved",
        "requester": "Clay Rowe",
        "monitoring_id": "94649",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 40,
        "red_app_id": "76074884",
        "cmpt_id": 77960665,
        "cmpt_name": "Unicode for C Sharp (Unicode4C)",
        "cmpt_version": "67.9",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "Unicode License V7",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "76654",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 41,
        "red_app_id": "76074884",
        "cmpt_id": 77960665,
        "cmpt_name": "Unicode for C Sharp (Unicode4C)",
        "cmpt_version": "67.9",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "Unicode License V7",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "76654",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 42,
        "red_app_id": "76074884",
        "cmpt_id": 69676778,
        "cmpt_name": "kassandra\/xerces-c",
        "cmpt_version": "6.7.7",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "48023",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 43,
        "red_app_id": "76074884",
        "cmpt_id": 69676778,
        "cmpt_name": "kassandra\/xerces-c",
        "cmpt_version": "6.7.7",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "48023",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 44,
        "red_app_id": "76074884",
        "cmpt_id": 755955,
        "cmpt_name": "Commons IO",
        "cmpt_version": "7.5",
        "app_id": 49823780,
        "app_name": "General ED",
        "app_version": "7.7.0.9",
        "license": "kassandra License 7.0",
        "status": "Rejected",
        "requester": "Barry Lind",
        "monitoring_id": "75896",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 45,
        "red_app_id": "76074884",
        "cmpt_id": 957948,
        "cmpt_name": "kassandra Commons Codec",
        "cmpt_version": "9.9",
        "app_id": 49823780,
        "app_name": "General ED",
        "app_version": "7.7.0.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Barry Lind",
        "monitoring_id": "76884",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 46,
        "red_app_id": "76074884",
        "cmpt_id": 9496865,
        "cmpt_name": "kassandra Jakarta Commons Codec",
        "cmpt_version": "9.6",
        "app_id": 80096980,
        "app_name": "General Te",
        "app_version": "96.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Clay Rowe",
        "monitoring_id": "9697",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 47,
        "red_app_id": "76074884",
        "cmpt_id": 7023877,
        "cmpt_name": "knockout - knockout\/knockout",
        "cmpt_version": "7.9.0",
        "app_id": 56704001,
        "app_name": "General Ac",
        "app_version": "4.0.9 - 5.0.0",
        "license": "MIT License",
        "status": "Submitted",
        "requester": "Clay Rowe",
        "monitoring_id": "94875",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 48,
        "red_app_id": "76074884",
        "cmpt_id": 7097666,
        "cmpt_name": "Oracle PHP API",
        "cmpt_version": "9.4.4",
        "app_id": 78784237,
        "app_name": "General Te",
        "app_version": "96.9",
        "license": "Unspecified",
        "status": "Approved",
        "requester": "Clay Rowe",
        "monitoring_id": "94649",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 49,
        "red_app_id": "76074884",
        "cmpt_id": 7097666,
        "cmpt_name": "Oracle PHP API",
        "cmpt_version": "9.4.4",
        "app_id": 78784237,
        "app_name": "General Te",
        "app_version": "96.9",
        "license": "Unspecified",
        "status": "Approved",
        "requester": "Clay Rowe",
        "monitoring_id": "94649",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 50,
        "red_app_id": "76074884",
        "cmpt_id": 77960665,
        "cmpt_name": "Unicode for C Sharp (Unicode4C)",
        "cmpt_version": "67.9",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "Unicode License V7",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "76654",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 51,
        "red_app_id": "76074884",
        "cmpt_id": 77960665,
        "cmpt_name": "Unicode for C Sharp (Unicode4C)",
        "cmpt_version": "67.9",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "Unicode License V7",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "76654",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 52,
        "red_app_id": "76074884",
        "cmpt_id": 69676778,
        "cmpt_name": "kassandra\/xerces-c",
        "cmpt_version": "6.7.7",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "48023",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 53,
        "red_app_id": "76074884",
        "cmpt_id": 69676778,
        "cmpt_name": "kassandra\/xerces-c",
        "cmpt_version": "6.7.7",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "48023",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 54,
        "red_app_id": "76074884",
        "cmpt_id": 755955,
        "cmpt_name": "Commons IO",
        "cmpt_version": "7.5",
        "app_id": 49823780,
        "app_name": "General ED",
        "app_version": "7.7.0.9",
        "license": "kassandra License 7.0",
        "status": "Rejected",
        "requester": "Barry Lind",
        "monitoring_id": "75896",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 55,
        "red_app_id": "76074884",
        "cmpt_id": 957948,
        "cmpt_name": "kassandra Commons Codec",
        "cmpt_version": "9.9",
        "app_id": 49823780,
        "app_name": "General ED",
        "app_version": "7.7.0.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Barry Lind",
        "monitoring_id": "76884",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 56,
        "red_app_id": "76074884",
        "cmpt_id": 9496865,
        "cmpt_name": "kassandra Jakarta Commons Codec",
        "cmpt_version": "9.6",
        "app_id": 80096980,
        "app_name": "General Te",
        "app_version": "96.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Clay Rowe",
        "monitoring_id": "9697",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 57,
        "red_app_id": "76074884",
        "cmpt_id": 7023877,
        "cmpt_name": "knockout - knockout\/knockout",
        "cmpt_version": "7.9.0",
        "app_id": 56704001,
        "app_name": "General Ac",
        "app_version": "4.0.9 - 5.0.0",
        "license": "MIT License",
        "status": "Submitted",
        "requester": "Clay Rowe",
        "monitoring_id": "94875",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 58,
        "red_app_id": "76074884",
        "cmpt_id": 7097666,
        "cmpt_name": "Oracle PHP API",
        "cmpt_version": "9.4.4",
        "app_id": 78784237,
        "app_name": "General Te",
        "app_version": "96.9",
        "license": "Unspecified",
        "status": "Approved",
        "requester": "Clay Rowe",
        "monitoring_id": "94649",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 59,
        "red_app_id": "76074884",
        "cmpt_id": 7097666,
        "cmpt_name": "Oracle PHP API",
        "cmpt_version": "9.4.4",
        "app_id": 78784237,
        "app_name": "General Te",
        "app_version": "96.9",
        "license": "Unspecified",
        "status": "Approved",
        "requester": "Clay Rowe",
        "monitoring_id": "94649",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 60,
        "red_app_id": "76074884",
        "cmpt_id": 77960665,
        "cmpt_name": "Unicode for C Sharp (Unicode4C)",
        "cmpt_version": "67.9",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "Unicode License V7",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "76654",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 61,
        "red_app_id": "76074884",
        "cmpt_id": 77960665,
        "cmpt_name": "Unicode for C Sharp (Unicode4C)",
        "cmpt_version": "67.9",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "Unicode License V7",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "76654",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 62,
        "red_app_id": "76074884",
        "cmpt_id": 69676778,
        "cmpt_name": "kassandra\/xerces-c",
        "cmpt_version": "6.7.7",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "48023",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 63,
        "red_app_id": "76074884",
        "cmpt_id": 69676778,
        "cmpt_name": "kassandra\/xerces-c",
        "cmpt_version": "6.7.7",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "48023",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 64,
        "red_app_id": "76074884",
        "cmpt_id": 755955,
        "cmpt_name": "Commons IO",
        "cmpt_version": "7.5",
        "app_id": 49823780,
        "app_name": "General ED",
        "app_version": "7.7.0.9",
        "license": "kassandra License 7.0",
        "status": "Rejected",
        "requester": "Barry Lind",
        "monitoring_id": "75896",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 65,
        "red_app_id": "76074884",
        "cmpt_id": 957948,
        "cmpt_name": "kassandra Commons Codec",
        "cmpt_version": "9.9",
        "app_id": 49823780,
        "app_name": "General ED",
        "app_version": "7.7.0.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Barry Lind",
        "monitoring_id": "76884",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 66,
        "red_app_id": "76074884",
        "cmpt_id": 9496865,
        "cmpt_name": "kassandra Jakarta Commons Codec",
        "cmpt_version": "9.6",
        "app_id": 80096980,
        "app_name": "General Te",
        "app_version": "96.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Clay Rowe",
        "monitoring_id": "9697",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 67,
        "red_app_id": "76074884",
        "cmpt_id": 7023877,
        "cmpt_name": "knockout - knockout\/knockout",
        "cmpt_version": "7.9.0",
        "app_id": 56704001,
        "app_name": "General Ac",
        "app_version": "4.0.9 - 5.0.0",
        "license": "MIT License",
        "status": "Submitted",
        "requester": "Clay Rowe",
        "monitoring_id": "94875",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 68,
        "red_app_id": "76074884",
        "cmpt_id": 7097666,
        "cmpt_name": "Oracle PHP API",
        "cmpt_version": "9.4.4",
        "app_id": 78784237,
        "app_name": "General Te",
        "app_version": "96.9",
        "license": "Unspecified",
        "status": "Approved",
        "requester": "Clay Rowe",
        "monitoring_id": "94649",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 69,
        "red_app_id": "76074884",
        "cmpt_id": 7097666,
        "cmpt_name": "Oracle PHP API",
        "cmpt_version": "9.4.4",
        "app_id": 78784237,
        "app_name": "General Te",
        "app_version": "96.9",
        "license": "Unspecified",
        "status": "Approved",
        "requester": "Clay Rowe",
        "monitoring_id": "94649",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 70,
        "red_app_id": "76074884",
        "cmpt_id": 77960665,
        "cmpt_name": "Unicode for C Sharp (Unicode4C)",
        "cmpt_version": "67.9",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "Unicode License V7",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "76654",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 71,
        "red_app_id": "76074884",
        "cmpt_id": 77960665,
        "cmpt_name": "Unicode for C Sharp (Unicode4C)",
        "cmpt_version": "67.9",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "Unicode License V7",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "76654",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 72,
        "red_app_id": "76074884",
        "cmpt_id": 69676778,
        "cmpt_name": "kassandra\/xerces-c",
        "cmpt_version": "6.7.7",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "48023",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 73,
        "red_app_id": "76074884",
        "cmpt_id": 69676778,
        "cmpt_name": "kassandra\/xerces-c",
        "cmpt_version": "6.7.7",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "48023",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 74,
        "red_app_id": "76074884",
        "cmpt_id": 755955,
        "cmpt_name": "Commons IO",
        "cmpt_version": "7.5",
        "app_id": 49823780,
        "app_name": "General ED",
        "app_version": "7.7.0.9",
        "license": "kassandra License 7.0",
        "status": "Rejected",
        "requester": "Barry Lind",
        "monitoring_id": "75896",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 75,
        "red_app_id": "76074884",
        "cmpt_id": 957948,
        "cmpt_name": "kassandra Commons Codec",
        "cmpt_version": "9.9",
        "app_id": 49823780,
        "app_name": "General ED",
        "app_version": "7.7.0.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Barry Lind",
        "monitoring_id": "76884",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 76,
        "red_app_id": "76074884",
        "cmpt_id": 9496865,
        "cmpt_name": "kassandra Jakarta Commons Codec",
        "cmpt_version": "9.6",
        "app_id": 80096980,
        "app_name": "General Te",
        "app_version": "96.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Clay Rowe",
        "monitoring_id": "9697",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 77,
        "red_app_id": "76074884",
        "cmpt_id": 7023877,
        "cmpt_name": "knockout - knockout\/knockout",
        "cmpt_version": "7.9.0",
        "app_id": 56704001,
        "app_name": "General Ac",
        "app_version": "4.0.9 - 5.0.0",
        "license": "MIT License",
        "status": "Submitted",
        "requester": "Clay Rowe",
        "monitoring_id": "94875",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 78,
        "red_app_id": "76074884",
        "cmpt_id": 7097666,
        "cmpt_name": "Oracle PHP API",
        "cmpt_version": "9.4.4",
        "app_id": 78784237,
        "app_name": "General Te",
        "app_version": "96.9",
        "license": "Unspecified",
        "status": "Approved",
        "requester": "Clay Rowe",
        "monitoring_id": "94649",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 79,
        "red_app_id": "76074884",
        "cmpt_id": 7097666,
        "cmpt_name": "Oracle PHP API",
        "cmpt_version": "9.4.4",
        "app_id": 78784237,
        "app_name": "General Te",
        "app_version": "96.9",
        "license": "Unspecified",
        "status": "Approved",
        "requester": "Clay Rowe",
        "monitoring_id": "94649",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 80,
        "red_app_id": "76074884",
        "cmpt_id": 77960665,
        "cmpt_name": "Unicode for C Sharp (Unicode4C)",
        "cmpt_version": "67.9",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "Unicode License V7",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "76654",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 81,
        "red_app_id": "76074884",
        "cmpt_id": 77960665,
        "cmpt_name": "Unicode for C Sharp (Unicode4C)",
        "cmpt_version": "67.9",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "Unicode License V7",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "76654",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 82,
        "red_app_id": "76074884",
        "cmpt_id": 69676778,
        "cmpt_name": "kassandra\/xerces-c",
        "cmpt_version": "6.7.7",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "48023",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 83,
        "red_app_id": "76074884",
        "cmpt_id": 69676778,
        "cmpt_name": "kassandra\/xerces-c",
        "cmpt_version": "6.7.7",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "48023",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 84,
        "red_app_id": "76074884",
        "cmpt_id": 755955,
        "cmpt_name": "Commons IO",
        "cmpt_version": "7.5",
        "app_id": 49823780,
        "app_name": "General ED",
        "app_version": "7.7.0.9",
        "license": "kassandra License 7.0",
        "status": "Rejected",
        "requester": "Barry Lind",
        "monitoring_id": "75896",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 85,
        "red_app_id": "76074884",
        "cmpt_id": 957948,
        "cmpt_name": "kassandra Commons Codec",
        "cmpt_version": "9.9",
        "app_id": 49823780,
        "app_name": "General ED",
        "app_version": "7.7.0.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Barry Lind",
        "monitoring_id": "76884",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 86,
        "red_app_id": "76074884",
        "cmpt_id": 9496865,
        "cmpt_name": "kassandra Jakarta Commons Codec",
        "cmpt_version": "9.6",
        "app_id": 80096980,
        "app_name": "General Te",
        "app_version": "96.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Clay Rowe",
        "monitoring_id": "9697",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 87,
        "red_app_id": "76074884",
        "cmpt_id": 7023877,
        "cmpt_name": "knockout - knockout\/knockout",
        "cmpt_version": "7.9.0",
        "app_id": 56704001,
        "app_name": "General Ac",
        "app_version": "4.0.9 - 5.0.0",
        "license": "MIT License",
        "status": "Submitted",
        "requester": "Clay Rowe",
        "monitoring_id": "94875",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 88,
        "red_app_id": "76074884",
        "cmpt_id": 7097666,
        "cmpt_name": "Oracle PHP API",
        "cmpt_version": "9.4.4",
        "app_id": 78784237,
        "app_name": "General Te",
        "app_version": "96.9",
        "license": "Unspecified",
        "status": "Approved",
        "requester": "Clay Rowe",
        "monitoring_id": "94649",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 89,
        "red_app_id": "76074884",
        "cmpt_id": 7097666,
        "cmpt_name": "Oracle PHP API",
        "cmpt_version": "9.4.4",
        "app_id": 78784237,
        "app_name": "General Te",
        "app_version": "96.9",
        "license": "Unspecified",
        "status": "Approved",
        "requester": "Clay Rowe",
        "monitoring_id": "94649",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 90,
        "red_app_id": "76074884",
        "cmpt_id": 77960665,
        "cmpt_name": "Unicode for C Sharp (Unicode4C)",
        "cmpt_version": "67.9",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "Unicode License V7",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "76654",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 91,
        "red_app_id": "76074884",
        "cmpt_id": 77960665,
        "cmpt_name": "Unicode for C Sharp (Unicode4C)",
        "cmpt_version": "67.9",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "Unicode License V7",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "76654",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 92,
        "red_app_id": "76074884",
        "cmpt_id": 69676778,
        "cmpt_name": "kassandra\/xerces-c",
        "cmpt_version": "6.7.7",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "48023",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 93,
        "red_app_id": "76074884",
        "cmpt_id": 69676778,
        "cmpt_name": "kassandra\/xerces-c",
        "cmpt_version": "6.7.7",
        "app_id": 77956768,
        "app_name": "LTS JSON L",
        "app_version": "9.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Tierra Von",
        "monitoring_id": "48023",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 94,
        "red_app_id": "76074884",
        "cmpt_id": 755955,
        "cmpt_name": "Commons IO",
        "cmpt_version": "7.5",
        "app_id": 49823780,
        "app_name": "General ED",
        "app_version": "7.7.0.9",
        "license": "kassandra License 7.0",
        "status": "Rejected",
        "requester": "Barry Lind",
        "monitoring_id": "75896",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 95,
        "red_app_id": "76074884",
        "cmpt_id": 957948,
        "cmpt_name": "kassandra Commons Codec",
        "cmpt_version": "9.9",
        "app_id": 49823780,
        "app_name": "General ED",
        "app_version": "7.7.0.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Barry Lind",
        "monitoring_id": "76884",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 96,
        "red_app_id": "76074884",
        "cmpt_id": 9496865,
        "cmpt_name": "kassandra Jakarta Commons Codec",
        "cmpt_version": "9.6",
        "app_id": 80096980,
        "app_name": "General Te",
        "app_version": "96.9",
        "license": "kassandra License 7.0",
        "status": "Approved",
        "requester": "Clay Rowe",
        "monitoring_id": "9697",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 97,
        "red_app_id": "76074884",
        "cmpt_id": 7023877,
        "cmpt_name": "knockout - knockout\/knockout",
        "cmpt_version": "7.9.0",
        "app_id": 56704001,
        "app_name": "General Ac",
        "app_version": "4.0.9 - 5.0.0",
        "license": "MIT License",
        "status": "Submitted",
        "requester": "Clay Rowe",
        "monitoring_id": "94875",
        "monitoring_digest": "na",
        "issue_count": "9"
    },
    {
        "line_id": 98,
        "red_app_id": "76074884",
        "cmpt_id": 7097666,
        "cmpt_name": "Oracle PHP API",
        "cmpt_version": "9.4.4",
        "app_id": 78784237,
        "app_name": "General Te",
        "app_version": "96.9",
        "license": "Unspecified",
        "status": "Approved",
        "requester": "Clay Rowe",
        "monitoring_id": "94649",
        "monitoring_digest": "na",
        "issue_count": "0"
    },
    {
        "line_id": 99,
        "red_app_id": "76074884",
        "cmpt_id": 7097666,
        "cmpt_name": "Oracle PHP API",
        "cmpt_version": "9.4.4",
        "app_id": 78784237,
        "app_name": "General Te",
        "app_version": "96.9",
        "license": "Unspecified",
        "status": "Approved",
        "requester": "Clay Rowe",
        "monitoring_id": "94649",
        "monitoring_digest": "na",
        "issue_count": "0"
    }
]